name: Code coverage

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Install ruby
      run: |
        sudo apt install ruby3.0-dev

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Add Ruby as external
      run: |
        spack -e tests external find --not-buildable ruby

    - name: Install spack environment
      run: |
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_COVERAGE=ON \
                 -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_BEDROCK=ON \
                 -DENABLE_PYTHON=ON \
                 -DENABLE_LUA=ON \
                 -DENABLE_RUBY=ON \
                 -DCMAKE_BUILD_TYPE=Debug
        make
        ctest --output-on-failure

    - name: Send coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
        gcov: true
