name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ruby
      run: |
        sudo apt install ruby3.0-dev

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Add Ruby as external
      run: |
        spack -e tests external find --not-buildable ruby

    - name: Install spack environment
      run: |
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_BEDROCK=ON \
                 -DENABLE_PYTHON=ON \
                 -DENABLE_LUA=ON \
                 -DENABLE_RUBY=ON \
                 -DCMAKE_BUILD_TYPE=RelWithDebInfo
        make
        ctest --output-on-failure

    - name: Push packages to buildcache and update index
      if: ${{ !cancelled() }}
      run: |
        spack -e tests mirror set --push \
        --oci-username ${{ github.actor }} \
        --oci-password "${{ secrets.GITHUB_TOKEN }}" mochi-buildcache
        spack -e tests buildcache push --base-image ubuntu:22.04 \
        --unsigned --update-index mochi-buildcache
